"""
This file contains the uniqueNames of artifacts organized by category and subcategory.
The structure mirrors artifact_foundry_names.py but uses uniqueNames instead of EN-US names.
This file is automatically generated by utils/item_search.py.
"""

ARTIFACT_UNIQUE_NAMES = {
    "Rune": {
        "Warrior": [
        ],
        "Mage": [
        ],
        "Hunter": [
        ],
    },
    "Soul": {
        "Warrior": [
        ],
        "Mage": [
        ],
        "Hunter": [
        ],
    },
    "Relic": {
        "Warrior": [
        ],
        "Mage": [
        ],
        "Hunter": [
        ],
    },
    "Avalonian Shard": {
        "Warrior": [
        ],
        "Mage": [
        ],
        "Hunter": [
        ],
    },
}
