# Rune Artifacts

# Warrior Rune Artifacts organized by tier
RUNE_WARRIOR_ARTIFACTS = {
    'T4': [
        'T4_ARTEFACT_SHOES_PLATE_UNDEAD',  # Ancient Bindings
        'T4_ARTEFACT_ARMOR_PLATE_UNDEAD',  # Ancient Chain Rings
        'T4_ARTEFACT_HEAD_PLATE_UNDEAD',   # Ancient Padding
        'T4_ARTEFACT_MAIN_SPEAR_KEEPER',   # Bloodforged Blade
        'T4_ARTEFACT_2H_HALBERD_MORGANA',  # Morgana Halberd Head
        'T4_ARTEFACT_MAIN_ROCKMACE_KEEPER', # Runed Rock
        'T4_ARTEFACT_MAIN_HAMMER_UNDEAD',  # Ancient Hammer Head
        'T4_ARTEFACT_OFF_SHIELD_UNDEAD',   # Ursine Guardian Remains
        'T4_ARTEFACT_2H_CROSSBOWLARGE_MORGANA', # Lost Crossbow Mechanism
        'T4_ARTEFACT_OFF_TOWERSHIELD_UNDEAD' # Ancient Shield Core
    ],
    'T5': [
        'T5_ARTEFACT_SHOES_PLATE_UNDEAD',
        'T5_ARTEFACT_ARMOR_PLATE_UNDEAD',
        'T5_ARTEFACT_HEAD_PLATE_UNDEAD',
        'T5_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T5_ARTEFACT_2H_HALBERD_MORGANA',
        'T5_ARTEFACT_MAIN_ROCKMACE_KEEPER',
        'T5_ARTEFACT_MAIN_HAMMER_UNDEAD',
        'T5_ARTEFACT_OFF_SHIELD_UNDEAD',
        'T5_ARTEFACT_2H_CROSSBOWLARGE_MORGANA',
        'T5_ARTEFACT_OFF_TOWERSHIELD_UNDEAD'
    ],
    'T6': [
        'T6_ARTEFACT_SHOES_PLATE_UNDEAD',
        'T6_ARTEFACT_ARMOR_PLATE_UNDEAD',
        'T6_ARTEFACT_HEAD_PLATE_UNDEAD',
        'T6_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T6_ARTEFACT_2H_HALBERD_MORGANA',
        'T6_ARTEFACT_MAIN_ROCKMACE_KEEPER',
        'T6_ARTEFACT_MAIN_HAMMER_UNDEAD',
        'T6_ARTEFACT_OFF_SHIELD_UNDEAD',
        'T6_ARTEFACT_2H_CROSSBOWLARGE_MORGANA',
        'T6_ARTEFACT_OFF_TOWERSHIELD_UNDEAD'
    ],
    'T7': [
        'T7_ARTEFACT_SHOES_PLATE_UNDEAD',
        'T7_ARTEFACT_ARMOR_PLATE_UNDEAD',
        'T7_ARTEFACT_HEAD_PLATE_UNDEAD',
        'T7_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T7_ARTEFACT_2H_HALBERD_MORGANA',
        'T7_ARTEFACT_MAIN_ROCKMACE_KEEPER',
        'T7_ARTEFACT_MAIN_HAMMER_UNDEAD',
        'T7_ARTEFACT_OFF_SHIELD_UNDEAD',
        'T7_ARTEFACT_2H_CROSSBOWLARGE_MORGANA',
        'T7_ARTEFACT_OFF_TOWERSHIELD_UNDEAD'
    ],
    'T8': [
        'T8_ARTEFACT_SHOES_PLATE_UNDEAD',
        'T8_ARTEFACT_ARMOR_PLATE_UNDEAD',
        'T8_ARTEFACT_HEAD_PLATE_UNDEAD',
        'T8_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T8_ARTEFACT_2H_HALBERD_MORGANA',
        'T8_ARTEFACT_MAIN_ROCKMACE_KEEPER',
        'T8_ARTEFACT_MAIN_HAMMER_UNDEAD',
        'T8_ARTEFACT_OFF_SHIELD_UNDEAD',
        'T8_ARTEFACT_2H_CROSSBOWLARGE_MORGANA',
        'T8_ARTEFACT_OFF_TOWERSHIELD_UNDEAD'
    ]
}

# Rune Hunter Artifacts organized by tier
RUNE_HUNTER_ARTIFACTS = {
    'T4': [
        'T4_ARTEFACT_SHOES_LEATHER_MORGANA',  # Imbued Soles
        'T4_ARTEFACT_ARMOR_LEATHER_MORGANA',  # Imbued Leather Folds
        'T4_ARTEFACT_HEAD_LEATHER_MORGANA',   # Imbued Visor
        'T4_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD', # Ghastly Arrows
        'T4_ARTEFACT_MAIN_SPEAR_KEEPER',     # Keeper Spearhead
        'T4_ARTEFACT_MAIN_NATURESTAFF_KEEPER', # Druidic Inscriptions
        'T4_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD', # Hardened Debole
        'T4_ARTEFACT_2H_ARCANESTAFF_HELL',   # Reinforced Morgana Pole
        'T4_ARTEFACT_MAIN_HORN_KEEPER'       # Runed Horn
    ],
    'T5': [
        'T5_ARTEFACT_SHOES_LEATHER_MORGANA',
        'T5_ARTEFACT_ARMOR_LEATHER_MORGANA',
        'T5_ARTEFACT_HEAD_LEATHER_MORGANA',
        'T5_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T5_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T5_ARTEFACT_MAIN_NATURESTAFF_KEEPER',
        'T5_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T5_ARTEFACT_2H_ARCANESTAFF_HELL',
        'T5_ARTEFACT_MAIN_HORN_KEEPER'
    ],
    'T6': [
        'T6_ARTEFACT_SHOES_LEATHER_MORGANA',
        'T6_ARTEFACT_ARMOR_LEATHER_MORGANA',
        'T6_ARTEFACT_HEAD_LEATHER_MORGANA',
        'T6_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T6_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T6_ARTEFACT_MAIN_NATURESTAFF_KEEPER',
        'T6_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T6_ARTEFACT_2H_ARCANESTAFF_HELL',
        'T6_ARTEFACT_MAIN_HORN_KEEPER'
    ],
    'T7': [
        'T7_ARTEFACT_SHOES_LEATHER_MORGANA',
        'T7_ARTEFACT_ARMOR_LEATHER_MORGANA',
        'T7_ARTEFACT_HEAD_LEATHER_MORGANA',
        'T7_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T7_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T7_ARTEFACT_MAIN_NATURESTAFF_KEEPER',
        'T7_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T7_ARTEFACT_2H_ARCANESTAFF_HELL',
        'T7_ARTEFACT_MAIN_HORN_KEEPER'
    ],
    'T8': [
        'T8_ARTEFACT_SHOES_LEATHER_MORGANA',
        'T8_ARTEFACT_ARMOR_LEATHER_MORGANA',
        'T8_ARTEFACT_HEAD_LEATHER_MORGANA',
        'T8_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T8_ARTEFACT_MAIN_SPEAR_KEEPER',
        'T8_ARTEFACT_MAIN_NATURESTAFF_KEEPER',
        'T8_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T8_ARTEFACT_2H_ARCANESTAFF_HELL',
        'T8_ARTEFACT_MAIN_HORN_KEEPER'
    ]
}

# Rune Mage Artifacts organized by tier
RUNE_MAGE_ARTIFACTS = {
    'T4': [
        'T4_ARTEFACT_SHOES_CLOTH_KEEPER',    # Druidic Bindings
        'T4_ARTEFACT_ARMOR_CLOTH_KEEPER',    # Druidic Feathers
        'T4_ARTEFACT_HEAD_CLOTH_KEEPER',     # Druidic Preserved Beak
        'T4_ARTEFACT_MAIN_FIRESTAFF_KEEPER', # Wildfire Orb
        'T4_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD', # Possessed Scroll
        'T4_ARTEFACT_MAIN_ARCANESTAFF_KEEPER', # Lost Arcane Crystal
        'T4_ARTEFACT_MAIN_FROSTSTAFF_KEEPER', # Hoarfrost Orb
        'T4_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD', # Lost Cursed Crystal
        'T4_ARTEFACT_MAIN_HOLYSTAFF_MORGANA'  # Alluring Crystal
    ],
    'T5': [
        'T5_ARTEFACT_SHOES_CLOTH_KEEPER',
        'T5_ARTEFACT_ARMOR_CLOTH_KEEPER',
        'T5_ARTEFACT_HEAD_CLOTH_KEEPER',
        'T5_ARTEFACT_MAIN_FIRESTAFF_KEEPER',
        'T5_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T5_ARTEFACT_MAIN_ARCANESTAFF_KEEPER',
        'T5_ARTEFACT_MAIN_FROSTSTAFF_KEEPER',
        'T5_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T5_ARTEFACT_MAIN_HOLYSTAFF_MORGANA'
    ],
    'T6': [
        'T6_ARTEFACT_SHOES_CLOTH_KEEPER',
        'T6_ARTEFACT_ARMOR_CLOTH_KEEPER',
        'T6_ARTEFACT_HEAD_CLOTH_KEEPER',
        'T6_ARTEFACT_MAIN_FIRESTAFF_KEEPER',
        'T6_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T6_ARTEFACT_MAIN_ARCANESTAFF_KEEPER',
        'T6_ARTEFACT_MAIN_FROSTSTAFF_KEEPER',
        'T6_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T6_ARTEFACT_MAIN_HOLYSTAFF_MORGANA'
    ],
    'T7': [
        'T7_ARTEFACT_SHOES_CLOTH_KEEPER',
        'T7_ARTEFACT_ARMOR_CLOTH_KEEPER',
        'T7_ARTEFACT_HEAD_CLOTH_KEEPER',
        'T7_ARTEFACT_MAIN_FIRESTAFF_KEEPER',
        'T7_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T7_ARTEFACT_MAIN_ARCANESTAFF_KEEPER',
        'T7_ARTEFACT_MAIN_FROSTSTAFF_KEEPER',
        'T7_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T7_ARTEFACT_MAIN_HOLYSTAFF_MORGANA'
    ],
    'T8': [
        'T8_ARTEFACT_SHOES_CLOTH_KEEPER',
        'T8_ARTEFACT_ARMOR_CLOTH_KEEPER',
        'T8_ARTEFACT_HEAD_CLOTH_KEEPER',
        'T8_ARTEFACT_MAIN_FIRESTAFF_KEEPER',
        'T8_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD',
        'T8_ARTEFACT_MAIN_ARCANESTAFF_KEEPER',
        'T8_ARTEFACT_MAIN_FROSTSTAFF_KEEPER',
        'T8_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD',
        'T8_ARTEFACT_MAIN_HOLYSTAFF_MORGANA'
    ]
}

def get_warrior_artifacts_by_tier(tier: str) -> list:
    """Get all warrior artifacts for a specific tier."""
    return RUNE_WARRIOR_ARTIFACTS.get(tier, [])

def get_hunter_artifacts_by_tier(tier: str) -> list:
    """Get all hunter artifacts for a specific tier."""
    return RUNE_HUNTER_ARTIFACTS.get(tier, [])

def get_mage_artifacts_by_tier(tier: str) -> list:
    """Get all mage artifacts for a specific tier."""
    return RUNE_MAGE_ARTIFACTS.get(tier, [])
